# Generated by Django 4.2.3 on 2023-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='MyAnimeList_username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
