# Generated by Django 4.2.3 on 2023-08-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
        ('users', '0010_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watched_anime',
            field=models.ManyToManyField(blank=True, to='anime.anime'),
        ),
    ]
